#!/usr/bin/env python3
"""Regenerate docs/assets/screenshots/INDEX.md from the SCREENSHOT comments in
docs/.

The index is a shopping list of the screenshots the documentation references
but does not yet ship. Each `<!-- SCREENSHOT: filename.png: description -->`
comment in `docs/` becomes one table row. Run this after adding or removing a
placeholder instead of hand-editing the index (which drifts):

    python3 scripts/gen_screenshot_index.py
"""
import glob
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.normpath(os.path.join(HERE, '..', 'docs'))
OUT = os.path.join(DOCS, 'assets', 'screenshots', 'INDEX.md')

# Capture <!-- SCREENSHOT: ... --> blocks (which may span several lines).
BLOCK = re.compile(r'<!--\s*SCREENSHOT:\s*(.*?)-->', re.DOTALL)
NAME = re.compile(r'^([\w.-]+\.png)\s*(\(optional\))?\s*:?\s*(.*)$', re.DOTALL)


def collect():
    rows = []  # (filename, page, description)
    for path in sorted(glob.glob(os.path.join(DOCS, '**', '*.md'), recursive=True)):
        if os.path.basename(path) == 'INDEX.md':
            continue
        page = os.path.relpath(path, DOCS).replace(os.sep, '/')
        with open(path, encoding='utf-8') as f:
            text = f.read()
        for m in BLOCK.finditer(text):
            body = ' '.join(m.group(1).split())  # collapse whitespace/newlines
            nm = NAME.match(body)
            if not nm:
                continue
            opt = ' (optional)' if nm.group(2) else ''
            rows.append((nm.group(1), page, nm.group(3).strip() + opt))
    return rows


def main():
    rows = collect()
    occurrences = len(rows)
    # One table row per unique filename (a screenshot referenced from two
    # places still only needs creating once).
    seen = {}
    for fname, page, desc in rows:
        seen.setdefault(fname, (fname, page, desc))
    unique_rows = sorted(seen.values(), key=lambda r: r[0])

    lines = [
        '# Screenshot Index\n',
        'This file is the shopping list for screenshots referenced',
        'throughout the documentation. Every entry below comes from a',
        '`<!-- SCREENSHOT: filename.png: description -->` comment in `docs/`.\n',
        '**To fill a placeholder**: drop a PNG matching the filename into',
        '`docs/assets/screenshots/`. The mkdocs build then resolves the',
        'image automatically; no edits to the markdown source needed.\n',
        '> Generated by `scripts/gen_screenshot_index.py`. After adding or',
        '> removing a placeholder, re-run it instead of hand-editing this file.\n',
        f'**Total placeholders:** {occurrences} references across '
        f'{len(unique_rows)} unique filenames\n',
        '## All screenshots\n',
        '| Filename | Page | Description |',
        '|----------|------|-------------|',
    ]
    for fname, page, desc in unique_rows:
        lines.append(f'| `{fname}` | `{page}` | {desc.replace("|", "\\|")} |')

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines).rstrip() + '\n')
    print(f'wrote {OUT}: {occurrences} references, {len(unique_rows)} unique filenames')


if __name__ == '__main__':
    main()
